server {
    listen 80;
    listen [::]:80;
    server_name byd.slk-soft.ru;
    root /www/wwwroot/byd.slk-soft.ru;
    client_max_body_size 32k;
    location ^~ /.well-known/acme-challenge/ { default_type text/plain; try_files $uri =404; }
    location / { return 503; }
}
